#!/bin/bash

version_file="/root/.pru/version"
pru_dir="/root/.pru"
initial_version="0.01"
current_version="0.02"

# Function to prompt user for update confirmation
prompt_update() {
    read -p "Update available. Do you want to update? (Y/N): " choice
    case "$choice" in
        y|Y ) echo "yiiha";;
        n|N ) echo "stopped"; exit;;
        * ) prompt_update;;
    esac
}

# Check if /root/.pru exists
if [ -d "$pru_dir" ]; then
    # Check if version file exists
    if [ -f "$version_file" ]; then
        # Read version from the version file
        versi=$(cat "$version_file")

        # Compare current_version with versi
        if [ "$(printf '%s\n' "$current_version" "$versi" | sort -V | head -n 1)" = "$current_version" ]; then
            prompt_update
        fi
    else
        # Create version file with initial version and set versi
        echo "$initial_version" > "$version_file"
        versi="$initial_version"
    fi
else
    # Create /root/.pru directory
    mkdir -p "$pru_dir"

    # Create version file with initial version and set versi
    echo "$initial_version" > "$version_file"
    versi="$initial_version"
fi

echo "Versi terkini: $current_version"
echo "Versi sedang digunakan: $versi"
