#!/bin/bash

version_file="/root/.pru/version"
pru_dir="/root/.pru"
initial_version="0.01"
current_version="0.03"

# Function to prompt user for update confirmation
prompt_update() {
    read -p "Update available. Do you want to update? (Y/N): " choice
    case "$choice" in
        y|Y ) echo "yiiha";;
        n|N ) echo "stopped"; exit;;
        * ) prompt_update;;
    esac
}

# Function to parse version into major and minor components
parse_version() {
    local version=$1
    major=$(echo "$version" | cut -d. -f1)
    minor=$(echo "$version" | cut -d. -f2)
}

# Check if /root/.pru exists
if [ -d "$pru_dir" ]; then
    # Check if version file exists
    if [ -f "$version_file" ]; then
        # Read version from the version file
        versi=$(cat "$version_file")
        parse_version "$current_version"
        current_major=$major
        current_minor=$minor
        parse_version "$versi"
        versi_major=$major
        versi_minor=$minor
        # Compare major and minor versions
        if [ "$current_major" -gt "$versi_major" ] || [ "$current_major" -eq "$versi_major" -a "$current_minor" -gt "$versi_minor" ]; then
echo "Versi terkini: $current_version"
        echo "Versi sedang digunakan: $versi"
prompt_update
        fi
    else
        # Create version file with initial version and set versi
        echo "$initial_version" > "$version_file"
        versi="$initial_version"

        echo "Versi terkini: $current_version"
        echo "Versi sedang digunakan: $versi"
    fi
else
    # Create /root/.pru directory
    mkdir -p "$pru_dir"

    # Create version file with initial version and set versi
    echo "$initial_version" > "$version_file"
    versi="$initial_version"

    echo "Versi terkini: $current_version"
    echo "Versi sedang digunakan: $versi"
fi
