#!/bin/sh
m=0
n=0
cat <<'E' >/bin/rewg
/etc/init.d/watchcat stop
n=$((n+1))
while [ $m -le 1 ]; do
/usr/lib/rooter/gcom/gcom-locked /dev/ttyUSB2 run-at.gcom 1 "AT+CFUN=1,1"
ifup wan && ifup wan1
sleep 90
ping6 -c 3 2001:4860:4860::8888
[ $? -eq 0 ] && /etc/init.d/watchcat start && /etc/init.d/watchcat enable && exit 0
m=$((m+1))
done
echo 1 > /proc/sys/kernel/sysrq
echo b > /proc/sysrq-trigger
E
chmod +x /bin/rewg
wget https://downloads.immortalwrt.org/releases/23.05.2/packages/aarch64_cortex-a53/packages/watchcat_1-17_all.ipk -O /tmp/wc.ipk
opkg install /tmp/wc.ipk
uci batch <<'E'
set watchcat.@watchcat[0].period='30s'
set watchcat.@watchcat[0].mode='run_script'
set watchcat.@watchcat[0].pinghosts='2001:4860:4860::8888'
set watchcat.@watchcat[0].addressfamily='ipv6'
set watchcat.@watchcat[0].pingperiod='6s'
set watchcat.@watchcat[0].script='/bin/rewg'
commit watchcat
E
/etc/init.d/watchcat start
/etc/init.d/watchcat enable
rm /tmp/wc.ipk
cat <<'E' >/bin/wcmon
#!/bin/sh
/etc/init.d/watchcat stop && /etc/init.d/watchcat disable
while true; do
curl -s --head http://example.com | grep "200 OK" > /dev/null && /etc/init.d/watchcat start && /etc/init.d/watchcat enable
sleep 60
done
E

chmod a+x /bin/wcmon
/bin/wcmon &
sed -i '/exit 0/i /bin/wcmon &' /etc/rc.local
echo "Watchcat IPv6 siap dipasang!"
